[env:cutretech-esp32s3]
custom_meshtastic_hw_model = 54
custom_meshtastic_hw_model_slug = EBYTE_ESP32_S3
custom_meshtastic_architecture = esp32-s3
custom_meshtastic_actively_supported = false
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = CutreTech ESP32-S3
custom_meshtastic_requires_dfu = true
custom_meshtastic_partition_scheme = 8MB

extends = esp32s3_base
board_level = extra
board = seeed-xiao-s3
board_build.partitions = default_8MB.csv
upload_protocol = esptool
upload_speed = 921600
build_flags =
  ${esp32s3_base.build_flags}
  -D EBYTE_ESP32_S3
  -I variants/esp32s3/cutretech-esp32s3
  -DBOARD_HAS_PSRAM