name: Build Firmware

on:
  workflow_dispatch:
    inputs:
      firmware_branch:
        description: "Branch or tag to checkout from meshtastic/firmware"
        required: true
        type: string
        default: "develop"
      variant:
        description: "Variant to build (e.g., cutretech-esp32s3)"
        required: true
        type: string

run-name: Build ${{ inputs.variant }}-${{ inputs.firmware_branch }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sanitize inputs
        run: |
          FIRMWARE_BRANCH="$(echo "${{ inputs.firmware_branch }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          VARIANT="$(echo "${{ inputs.variant }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          FIRMWARE_ARCHIVE="firmware-${VARIANT}-${FIRMWARE_BRANCH}.tar.xz"

          echo "FIRMWARE_BRANCH=${FIRMWARE_BRANCH}" >> "$GITHUB_ENV"
          echo "VARIANT=${VARIANT}" >> "$GITHUB_ENV"
          echo "FIRMWARE_ARCHIVE=${FIRMWARE_ARCHIVE}" >> "$GITHUB_ENV"

      - name: Checkout this repository
        uses: actions/checkout@v7
        with:
          path: builder

      - name: Checkout meshtastic/firmware
        uses: actions/checkout@v7
        with:
          repository: meshtastic/firmware
          ref: ${{ env.FIRMWARE_BRANCH }}
          path: firmware
          submodules: recursive

      - name: Copy variants folder
        run: cp -r builder/variants/* firmware/variants/

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Build firmware
        working-directory: firmware
        run:  pio run -e "${VARIANT}" --disable-auto-clean


      - name: Create firmware archive
        run: |
          cd firmware/.pio/build/"${VARIANT}"
          shopt -s nullglob
          files=(*.bin *.uf2)
          tar -cJf "${FIRMWARE_ARCHIVE}" "${files[@]}"

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.FIRMWARE_ARCHIVE }}
          path: firmware/.pio/build/${{ env.VARIANT }}/${{ env.FIRMWARE_ARCHIVE }}
          archive: false
          if-no-files-found: error
